### ISSUE TITLE
Compilation failure, BackstringIterator is not abstract

### ISSUE THREAD

**Issue by caver115** [MassiveCraft/MassiveCore#201]
Commit: 23d11564244e7363fa187e61108fad2da1d26d7f

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project MassiveCore: Compilation failure
[ERROR] /home/caver/MassiveCore/src/main/java/com/massivecraft/massivecore/collections/BackstringIterator.java:[5,8] com.massivecraft.massivecore.collections.BackstringIterator is not abstract and does not override abstract method remove() in java.util.Iterator

**Comment by Byteflux** [comment]
@oloflarsson It seems likely to me that you are not using Maven to build since I noticed that often MassiveCore stuff doesn't compile in Maven.

This particular issue is because you compile with Java 8, but some of us are using a prior version. In my case, I'm using Java 7. The -source and -target are set to 1.6 in Maven's POM, so I'm guessing that you aren't using Maven to compile.

Fix is easy in BackStringIterator:
```java
	@Override
	public void remove()
	{
		throw new UnsupportedOperationException();
	}
```

**Comment by oloflarsson** [comment]
@Byteflux - I use Maven to compile :smile_cat:. Thanks for the suggested Java 7 fix.
