### ISSUE TITLE
Internal Exception: io.netty.handler.codec.decoder.Exception: com.google.gson.JsonSyntaxException: Expected ':' at line 1 column 44

### ISSUE THREAD

**Issue by IlPicasso** [MassiveCraft/MassiveCore#212]
http://gyazo.com/94d720a4129a39b6928655b4505cb13c

Title says it all

I am running lastest Mcore and factions

I use MongoDB actually.

I don't know what is happening but it kicks randomly a group of players from time to time, no errors in the console which makes me get more worried.

Support is appreciated!

I use FactionTax too ;D

**Comment by magnusulf** [comment]
Never say you use the latest version, it changes from time to time and you can never be sure.
Which version of CraftBukkit/Spigot/whatever are you running (if spigot 1.8 please state approximately  the day it was build, since it updates all the time).
What usually causes this to happen (entering territory, changing world, performing command etc)
Are you sure the configuration file is configured correctly (sometimes incorrectly changing the config cause it to not be loaded properly).

**Comment by IlPicasso** [comment]
Well I can assure factions is 2.7.5

Probably I have to update Spigot

http://gyazo.com/6e01ff942e52dca33fd0f13e94949229


I don't need to move, I get kicked even after being AFK.


(No error Log)

I can not assure if the config is well setup, I will give a look again, in a few hours

About the configs, I can't be sure if something is wrong

**Comment by oloflarsson** [comment]
Update Spigot and see if that helps. If id does not, try removing the MassiveCore and Factions mstore files and plugin folders to start over with new data. Maybe some database files got corrupted, but I doubt this error that you see has anything to do with my plugins.
