### ISSUE TITLE
Factions Problem (With MassiveCore)

### ISSUE THREAD

**Issue by timeist** [MassiveCraft/MassiveCore#269]
So I deleted the two files for factions and massivecore, but now my chat users look like this. 
![2016-07-09_16 47 27](https://cloud.githubusercontent.com/assets/20374771/16710221/09681eca-45f5-11e6-914d-358ee2cf4da5.png)   I have AdvancedSounds ArmorStandEditor AutoRank BarAPI BiteSkywars BossBarMessage BossBarAutoMessage BuycraftX ChairStairs Clearlag ColoredSigns ColeredTablist CommandCooldown-Master CommandSpy CompatNoCheatPlus ConsoleScheduler CoreProtect CS-CoreLib CustomTab CustomRecipes EnjinMinecraft Essentials (GeoIP and xmpp too) GroupManager HolographicDisplays Jobs LibsDisguises LobbyCompass mcMMO MultiINV Multiverse (Portals too) NametagEDIT neoPAINT nocheatplus NoWeather OreObfuscator PerWolrdChatPlus PerWorldPlugins ProtocolLib Punishmental ScreenText Ships SignColors SignShop SimpleAutoBroadcast SimplePets SkyWars StaleAPI SuperPotions SuperTrails Tablist TheMaze TuxTwoLib update Updater Vault WGCuston WGFlyFlags WizardlyMagic WorldEdit WorldGuard
CAn you please help me figure out what the problem is?

**Comment by ulumulu1510** [comment]
The placeholders that you see in your chat for faction related stuff is not getting replaced anymore since you deleted factions and massivecore. If you use a decent chat management plugin you should be able to configure it to not show faction related prefixes anymore.

If you need further help, I advise you to go to ask st the chat managing plugins page.
