### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Bodyash** [MassiveCraft/MassiveCore#271]
I dont have enough info, but spigot forum says thats the MassiveCore is the problem
http://pastebin.com/gVEVTiCN

**Comment by SirFaizdat** [comment]
This line keeps coming up:

`com.massivecraft.massivecore.store.PusherCollFlatfile.run(PusherCollFlatfile.java:56)`

**Comment by oloflarsson** [comment]
This is the relevant section: https://gyazo.com/26c5f510736ad6e26d365a6f69e2aa99
The main server thread is locked waiting on a vanilla feature. I don't see any evidence this is caused by MassiveCore. It could be caused by invalid parallel programming by any plugin. I have never seen this error on my own server so the issue is probably elsewhere.
