### ISSUE TITLE
How can I disable the class BoardUtil and EngineMassiveCoreCollTick?

### ISSUE THREAD

**Issue by nathampa0909** [MassiveCraft/MassiveCore#282]
Hello, this two classes are causing lag on my server. I saw that class BoardUtil is a ScoreBoard but I use a plugin for ScoreBoard. The other class I don't know what it doing.

http://image.prntscr.com/image/48a1b465042543a0827c6ebb9134be5d.jpeg

OBS: I will resolve the lag of SimpleClans but MassiveCore is lagging +/- 10% of total.

**Comment by MarkehMe** [comment]
Can you show us how BoardUtil is being used?

**Comment by nathampa0909** [comment]
@MarkehMe I don't know, because Timings only show the thread equal in print I send.

**Comment by ulumulu1510** [comment]
BoardColl can'teach be deactivated, neither so the EngineTick.

If you use MassiveCombat,  you will need the BoardColl running. Otherwise, yes you might not need it but there is currently no way of shutting it down.

The EngineTick is crucial to all listeners and tI'm ed things in our plugins, it is impossible to get rid of it.

**Comment by nathampa0909** [comment]
@ulumulu1510 I only use the MassiveCore and CreativeGates. But thanks for reply!
