### ISSUE TITLE
MassiveCore v2.9.0 - CraftBukkit version git-Spigot-f950f8e-58bff62 (MC: 1.11)

### ISSUE THREAD

**Issue by DaDMaR** [MassiveCraft/MassiveCore#284]
[latest - Copy2.log.txt](https://github.com/MassiveCraft/MassiveCore/files/638025/latest.-.Copy2.log.txt)

**Comment by DaDMaR** [comment]
not fixed yet - for MC1.11 ??? - thanks for great plugin

**Comment by ulumulu1510** [comment]
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125) ~[spigot-1.11.jar:git-Spigot-f950f8e-58bff62]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67) ~[spigot-1.11.jar:git-Spigot-f950f8e-58bff62]
	at com.nitnelave.CreeperHeal.CreeperHeal.<init>

So what I am suspecting is that you either have two instances of MassiveCore running or that Creeperheal is somehow intefreering with this.

Becuase the initialization error was caused by CreeperHeal, as you can see in this log. Please make a clean install on a seperate test server and remove creeperheal from your plugins and report back if the issue persist.

Also, don't open a new issue every time you encounter an error and please use pastebin in the future as it is hard to search though a txt file.

**Comment by DaDMaR** [comment]
Thank you for your reply - Both do work with out each other. - have posted to nitnelave author of CreeperHeal

Quote "So what I am suspecting is that you either have two instances of MassiveCore running or that Creeperheal is somehow intefreering with this."

I believe I may have had two instances of MassiveCore at the time - not sure - as I had just updated to the newest version. 

[http://pastebin.com/mJQPHWmF](url) Latest error with both trying to run
