### ISSUE TITLE
Entity custom data

### ISSUE THREAD

**Issue by ItsHarry** [MassiveCraft/MassiveCore#286]
It seems that custom data for entities was removed in version 2.8: https://github.com/MassiveCraft/MassiveCore/commit/dbb79ba297e457a783814605efb5d8cc96c34f3c

Was it replaced by a new API or is the functionality simply gone? I need it for one of my plugins

**Comment by ulumulu1510** [comment]
The functionality was not replaced,  we have not received any feedback that it was needed at all.

Depending on what you use it for, it is better two create another Entity and Coll for your needs.

If you want, we can discuss your usage and if we both feel it would be best to re-implement this costume data in some way, I would coin it in the next Dev discussion we have.

Remember though,  it was removed because that part of the Entity loaded slowly and thus this part seemed unperformant.

**Comment by ItsHarry** [comment]
Specifically I want to save a "score" for each Faction (MassiveCraft's Factions plugin). I'm using a custom build of MassiveCore 2.8 now that still has the custom data implemented.

If I'm the only person using this functionality then I wouldn't want to waste your guys' time on it. Could always save the data in a separate database

**Comment by MarkehMe** [comment]
It may be worthwhile saving it in a seperate database as you never know how the future of how MassiveCore database will change - not that anything is planned (that i'm aware of) but it's always best to be safe than sorry! 

I have created something similar to work between Sponge and Bukkit, [Rson](https://github.com/redstone/Rson), if you would like to use it!

**Comment by oloflarsson** [comment]
You could decompile and take a look at FactionsTax. In there you can see how we handle "extra data". We make an entirely new collection with entities using the same ids.

**Comment by oloflarsson** [comment]
I'm closing this issue now since we are not going to implement custom data storage in this way.
