### ISSUE TITLE
Server TPS util - Feature request

### ISSUE THREAD

**Issue by Dienns** [MassiveCraft/MassiveCore#289]
Hi,

I'm currently using MassiveCore as a fun project for customization.
I find it weird that SpigotMC does not have a default function for getting server TPS, or I simply can't find it.

I think it would be a nice idea for this to be implemented into MassiveCore.
A simple util for getting the current TPS, and possible keep a history of it.

If there's already something for it, then please notify me.

Regards

**Comment by ulumulu1510** [comment]
Hey :)

We have a premium resource on Spigot taking care of that and other loads of other tasks:
https://www.spigotmc.org/resources/massivelag.11257/

MassiveLag is a revolutionary Lag and TPS diagnostics plugin. Its specialty is detecting why you have performance issues. It will tell you exactly where those lag spikes and TPS drops are coming from.

It is keeping a history of the last couple seconds and gathers timings from lag spikes autmatically. It's a great diagnostic tool to use on your own plugins.

Regards,
Ulumulu1510

**Comment by Dienns** [comment]
I requested a feature, not some guy trying to sell me a plugin.
I asked for a simple method returning the current server TPS, not an entire diagnostics tool.

**Comment by SirFaizdat** [comment]
@Dienns Perhaps you could use Spigot/Minecraft server to get the TPS. [This thread](https://www.spigotmc.org/threads/solved-get-tps-from-spigot.49886/#post-559536) may help you.

**Comment by ulumulu1510** [comment]
This turned from a polite request and polite answer to a harsh comment rather fast.

"Some guy" is co-creator of MassiveCore and well aware that this is a full fledged diagnostics tool. We have the code in there to analyze tps and we didn't put that into our open source code base because we have a whole project dedicated to it.

So in regards to that, we will not include this feature in MassiveCore unless it's needed by any of our other plugins. And afterall, MassiveCore is open source, someone can make a PR about it if that is their wish.

**Comment by Dienns** [comment]
I already created a custom engine for simply receiving the TPS.
I feel like I'm still being misunderstood, that's why I gave a harsch reply;

I asked for one simple method that returns the current server TPS, no diagnostics, no history, nothing fancy or special.

Trying to sell something instead of simply responding to my question, _that_ is rude if you ask me.
Anyhow, fixed the issue myself. Apologies for any harsch responses, it wasn't meant that way.
