### ISSUE TITLE
Disabling Vampire for Worlds

### ISSUE THREAD

**Issue by prophetnoble** [MassiveCraft/MassiveCore#7]
Ok I have a Normal World and a MiniGames World and I would like to disable vampire for minigames world I have put them in there own mcore Mutiverse Normal World is In Vampire Mutiverse Will all apects and Minigames  is in Normal Mutliverse witch  has no aspects but people still burn. Please Help Lead / help me tell want I did or Don't Do.

**Comment by killyouslow** [comment]
its not your fault, the owner removed the ability to disable aspects per multiverse, soo chances are if you pointed the apect to use a certain multiverse and not another than YOU DID EVERYTHING RIGHT, the problem is that mcore doesnt work at all, and you cant disable aspects anymore because the plugin manager messed up, also you'll get no help here, oloflarsson is allergic to people who point out his failures.

**Comment by ulumulu1510** [comment]
@killyouslow

I am not sure why you spread your foul words and missinformation over so many github issues but one thing is certain:

With your attitude, you don't get anywhere.


Fact is, that Cayorion developes plugins foremost for his own usage and he does grant others to use some of this work. This work is subject to changes, as everything is, and one of these changes was to disable the usys since he had no use for it anymore. (The world exception set proved to be more usefull)

As a person I can understand that you are unhappy and miss certain features. As a developer I cannot understand the attitude you aproach us with. You don't seem to understand that developers don't owe you anything. Not changes, nor new features.

Last, but not least, the "failures" you pointed out only evolve from your lack of perspective and gratefullness.

Tl;DR:
Watch your attitude and stop posting spite all over the issue tracker.

**Comment by killyouslow** [comment]
I'm not withholding any "attitude" because i already know i'm not gonna get any help from anyone here regardless, so why spare any frustrations.

second, your views are your own. as are mine.

I feel like the plugin authors owe the community for their contributions to the projects, we use the plugins, we promote the plugins, we purchase the plugins. as far as i'm concerned your argument that you owe us "nothing" is much more selfish than my philosophy and standing points
